export const PERMISSIONS = {
  ORGANIZATION_READ: "organization:read",
  ORGANIZATION_UPDATE: "organization:update",

  MEMBERS_READ: "members:read",
  MEMBERS_MANAGE: "members:manage",
  MEMBERS_ROLE_UPDATE: "members:role:update",

  ORGANIZATION_DELETE: "organization:delete",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS = {
  OWNER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.MEMBERS_ROLE_UPDATE,
    PERMISSIONS.ORGANIZATION_DELETE,
  ],

  ADMIN: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_MANAGE,
  ],

  MEMBER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.MEMBERS_READ,
  ],
} as const;
